### PR TITLE
Fix disabling GPU use

### LINKED ISSUE #55: --disableGpu not working
`--disableGpu` flag is not working at the moment

### PR DESCRIPTION
**Pull request by jehna**
Fixes #55 

Need to check what happens to test run times if [e161521](https://github.com/jehna/humanify/pull/56/commits/e161521d1764b32f7e189808e7edc198bf5102d2) is applied, best case they stay at ~5min

### CODE REVIEW

**Comment by jehna** [comment]
No effect in CI test runs, this is good to go 🚀

File: src/commands/local.ts [hunk 1]
```diff
@@ -25,9 +25,11 @@ export const local = cli()
       verbose.enabled = true;
     }
 
+    verbose.log("Starting local inference with options: ", opts);
+
     const prompt = await llama({
       model: opts.model,
-      disableGPU: opts.disableGPU,
+      disableGpu: opts.disableGpu,
```
Comment (0xdevalias) [inline src/commands/local.ts:32]: Should the TypeScript typing have pointed out this issue earlier?

File: src/plugins/local-llm-rename/llama.ts [hunk 2]
```diff
@@ -13,13 +19,16 @@ const IS_CI = process.env["CI"] === "true";
...
 }): Promise<Prompt> {
-  const llama = await getLlama();
-  const model = await llama.loadModel({
+  const disableGpu = opts.disableGpu ?? IS_CI;
+  const llama = await getLlama({ gpu: disableGpu ? false : "auto" });
+  const modelOpts: LlamaModelOptions = {
     modelPath: getModelPath(opts?.model),
-    gpuLayers: (opts?.disableGPU ?? IS_CI) ? 0 : undefined
-  });
+    gpuLayers: disableGpu ? 0 : undefined
```
Comment (0xdevalias) [inline src/plugins/local-llm-rename/llama.ts:28]: Curious, if GPU is disabled in the call to `getLlama`, do you actually need to set `gpuLayers` to `0` here? Or is this just leftover from your previous attempted approach to disable GPU?

File: src/commands/local.ts (hunk 1 above)
Comment (jehna) [reply src/commands/local.ts:32]: Yes, but unfortunately the `commander` package just passes `any` as the options. `yargs` was better in making the options strongly typed, although I found the `commander` package a bit more ergonomic to use. I'm thinking about changing away from `commander` though, exactly because this should have been a compiler-caught bug.

Comment (0xdevalias) [reply src/commands/local.ts:32]: Ah true; yeah, that makes sense.

**Comment by neoOpus** [comment]
Right now without GPU it just do not work at all

```
humanify local --verbose -m 2b --disableGpu .\arkose.js
[2024-09-11 19:12:07]  Starting local inference with options:  { model: '2b', outputDir: 'output', verbose: true, disableGpu: true }
[2024-09-11 19:12:07]  Loading model with options {
  modelPath: 'C:\\Users\\neoop\\.humanifyjs\\models/Phi-3.1-mini-4k-instruct-Q4_K_M.gguf',
  gpuLayers: 0
}
```

**Comment by jehna** [comment]
That's weird. I do run CI tests without GPU and they seem to be working fine. Do you get any errors? Running even a small model on a mid renage CPU is super slow though.

**Comment by neoOpus** [comment]
Maybe because I am using an old laptop, I don't have access to another for the moment... 

No, I didn't get any error... I would like to know what is the problem in order to try to fix it.

Yes, I am aware of LLM being extremely slow as I try to use AnythingLLM to try some uncensored models...

**Comment by jehna** [comment]
Does the program exit by itself or does it just seem to hang forever? If it exits, what's the exit code?

**Comment by neoOpus** [comment]
> Does the program exit by itself or does it just seem to hang forever? If it exits, what's the exit code?

Yes it exists just after I launch it...

**Comment by neoOpus** [comment]
I managed to make this work via WSL by installing all the required components (I have to write a tutorial about this, but I need to setup another machine to start from scratch and take note of all steps)... So for the moment you can just forget about this issue...

Side note : I will add support in the code "disableGPU" as well as I think it is more appropriate to write it and do PR.
